# file: .github/workflows/ci.yml

# Name of the workflow
name: Marko iOS CI

# Controls when the workflow will run
on:
  # Triggers on push events for any branch NOT named master
  push:
    branches-ignore:
      - 'master'
  # Triggers on pull request events targeted at the develop branch
  pull_request:
    branches:
      - 'develop'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
      # Step 1: Checks-out your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Select the correct version of Xcode
      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.4'
          
      # Step 3: Build the app using your xcworkspace
      - name: Build project
        run: |
          xcodebuild build -workspace Marko.xcworkspace \
                     -scheme Marko \
                     -destination 'platform=iOS Simulator,name=iPhone 8,OS=14.4'
