# file: .github/workflows/ci.yml

name: Marko iOS CI

on:
  push:
    branches-ignore:
      - 'master'
  pull_request:
    branches:
      - 'develop'

jobs:
  build:
    # --- THIS IS THE FIX ---
    # Use an older runner image that has Xcode 12.4 available.
    runs-on: macos-11

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.4'
          
      - name: Build project
        run: |
          xcodebuild build -workspace Marko.xcworkspace \
                     -scheme Marko \
                     -destination 'platform=iOS Simulator,name=iPhone 8,OS=14.4'
