name: iOS CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: macos-14 # GitHub runner with Xcode 15 preinstalled

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Select Xcode 15
        run: sudo xcode-select -s "/Applications/Xcode_15.2.app"

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Build for simulator (iOS 17)
        run: |
          xcodebuild \
            -scheme Marko \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,OS=17.0,name=iPhone 15' \
            clean build | xcpretty
