# file: .github/workflows/ci.yml

name: Marko iOS CI

on:
  push:
    branches-ignore:
      - 'master'
  pull_request:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'
          
      # --- CORRECTED BUILD COMMAND ---
      # Use the .xcodeproj because CocoaPods is not yet installed.
      - name: Build project
        run: |
          xcodebuild build -project Marko/Marko.xcodeproj \
                     -scheme Marko \
                     -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0'
