name: iOS CI & Jira Automation

on:
  push:
    branches: [ develop ]
  pull_request:
    types: [opened, closed]
    branches: [ develop ]

jobs:
  build:
    name: Build Project
    runs-on: macos-14
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Select Xcode 15
        run: sudo xcode-select -s "/Applications/Xcode_15.2.app"
      - name: Build for simulator
        run: |
          xcodebuild \
            -scheme Marko \
            -project Marko.xcodeproj \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
            clean build

  jira-transition:
    name: Update Jira Ticket
    if: github.event_name == 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Get Jira Key from Branch Name
        id: get-jira-key
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Branch Name: $BRANCH_NAME"
          JIRA_KEY=$(echo "$BRANCH_NAME" | grep -o -E '[A-Z]+-[0-9]+')
          if [ -z "$JIRA_KEY" ]; then
            echo "Jira Key not found in branch name."
            echo "JIRA_KEY=" >> $GITHUB_OUTPUT
          else
            echo "Jira Key Found: $JIRA_KEY"
            echo "JIRA_KEY=$JIRA_KEY" >> $GITHUB_OUTPUT
          fi

      - name: Transition Jira Issue to 'In Progress'
        # This step only runs if a PR was opened AND a Jira key was found
        if: github.event.action == 'opened' && steps.get-jira-key.outputs.JIRA_KEY != ''
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.get-jira-key.outputs.JIRA_KEY }}
          transition: "In Progress"
          login: ${{ secrets.JIRA_USER_EMAIL }}
          password: ${{ secrets.JIRA_API_TOKEN }}
          site: ${{ secrets.JIRA_BASE_URL }}
          
      - name: Transition Jira Issue to 'Done'
        # This step only runs if a PR was closed/merged AND a Jira key was found
        if: github.event.action == 'closed' && github.event.pull_request.merged == true && steps.get-jira-key.outputs.JIRA_KEY != ''
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.get-jira-key.outputs.JIRA_KEY }}
          transition: "Done"
          login: ${{ secrets.JIRA_USER_EMAIL }}
          password: ${{ secrets.JIRA_API_TOKEN }}
          site: ${{ secrets.JIRA_BASE_URL }}


#name: iOS CI & Jira Automation
#
#on:
#  push:
#    branches: [ develop ]
#  pull_request:
#    types: [opened, closed]
#    branches: [ develop ]
#
#jobs:
#  build:
#    name: Build Project
#    runs-on: macos-14
#    steps:
#      - name: Checkout source
#        uses: actions/checkout@v4
#
#      - name: Select Xcode 15
#        run: sudo xcode-select -s "/Applications/Xcode_15.2.app"
#
#      - name: Build for simulator
#        run: |
#          xcodebuild \
#            -scheme Marko \
#            -project Marko.xcodeproj \
#            -sdk iphonesimulator \
#            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
#            clean build
#
#  jira-transition:
#    name: Update Jira Ticket
#    # This job only runs on pull request events, not pushes
#    if: github.event_name == 'pull_request'
#    needs: build
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Get Jira Key from Branch Name
#        id: get-jira-key
#        run: |
#          # Get the branch name from the pull request event
#          BRANCH_NAME="${{ github.head_ref }}"
#          # Use grep to find a pattern like MRK-123
#          JIRA_KEY=$(echo "$BRANCH_NAME" | grep -o -E '[A-Z]+-[0-9]+')
#          echo "JIRA_KEY=${JIRA_KEY}" >> $GITHUB_OUTPUT
#
#      - name: Transition Jira Issue to 'In Progress'
#        # This step only runs if a PR was opened AND a Jira key was found
#        if: github.event.action == 'opened' && steps.get-jira-key.outputs.JIRA_KEY != ''
#        uses: atlassian/gajira-transition@v3
#        with:
#          issue: ${{ steps.get-jira-key.outputs.JIRA_KEY }}
#          transition: "In Progress"
#          login: ${{ secrets.JIRA_USER_EMAIL }}
#          password: ${{ secrets.JIRA_API_TOKEN }}
#          site: ${{ secrets.JIRA_BASE_URL }}
#
#      - name: Transition Jira Issue to 'Done'
#        # This step only runs if a PR was closed/merged AND a Jira key was found
#        if: github.event.action == 'closed' && github.event.pull_request.merged == true && steps.get-jira-key.outputs.JIRA_KEY != ''
#        uses: atlassian/gajira-transition@v3
#        with:
#          issue: ${{ steps.get-jira-key.outputs.JIRA_KEY }}
#          transition: "Done"
#          login: ${{ secrets.JIRA_USER_EMAIL }}
#          password: ${{ secrets.JIRA_API_TOKEN }}
#          site: ${{ secrets.JIRA_BASE_URL }}
