# file: .github/workflows/ci.yml

name: Marko iOS CI

on:
  push:
    branches-ignore:
      - 'master'
  pull_request:
    branches:
      - 'develop'

jobs:
  build:
    # Use the latest stable macOS runner
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Select the oldest available STABLE Xcode version from the runner's list.
      # As of the error log, '16.0' is a good choice.
      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'
          
      # Build the project. We will address any code compatibility issues next.
      - name: Build project
        run: |
          xcodebuild build -workspace Marko.xcworkspace \
                     -scheme Marko \
                     -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0'
